# Configuration for CC2500 Shield V2.0 on Wemos D1 mini

external_components:
  - source: github://rrooggiieerr/esphome-cc2500@main
    components: [cc2500]

spi:
  id: cc2500_spi
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

cc2500:
  spi_id: cc2500_spi
  cs_pin: GPIO16
  gdo0_pin: A0 # Temperature
  gdo2_pin: GPIO15 # Interrupt
  output_power: 0xFF

sensor:
  - platform: cc2500
    temperature:
      id: cc2500_temperature
      name: CC2500 Temperature
      update_interval: 5s
      entity_category: diagnostic
      disabled_by_default: True
